# Generated by Django 6.0.3 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido de Texto'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF / Documento'), ('powerpoint', 'Presentación (PPT/PPTX)'), ('text', 'Texto / Lectura')], max_length=20, verbose_name='Tipo de Contenido'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_content/', verbose_name='Archivo'),
        ),
    ]
