# Generated by Django 6.0.3 on 2026-04-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_content_text_content_alter_content_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lms.course'),
            preserve_default=False,
        ),
    ]
