# Generated by Django 6.0.3 on 2026-04-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_test_module_test_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lms.course'),
        ),
    ]
