# Generated by Django 6.0.3 on 2026-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_test_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headquarters',
            field=models.CharField(choices=[('Hualpen', 'Hualpén'), ('Coyhaique', 'Coyhaique')], default='Hualpen', max_length=50, verbose_name='Sede'),
        ),
    ]
