# Generated by Django 6.0.3 on 2026-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_userprofile_headquarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID de Colaborador'),
        ),
    ]
