# Generated by Django 6.0.3 on 2026-05-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_userprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
