# Generated by Django 6.0.3 on 2026-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_enrollment_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Plazo de Entrega'),
        ),
    ]
