# Generated by Django 6.0.3 on 2026-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_test_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Plazo para completar (días)'),
        ),
    ]
