# Generated by Django 6.0.3 on 2026-07-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_course_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('observacion', 'Observación'), ('pendiente', 'Pendiente'), ('evaluacion', 'Evaluación'), ('incidente', 'Incidente')], max_length=20, verbose_name='Tipo de Registro')),
                ('resident_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Residente (Opcional)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
