# Generated by Django 6.0.3 on 2026-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_bitacoraentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraentry',
            name='incident_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos Adicionales del Incidente'),
        ),
    ]
