[app_server]
3.85.176.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key

[webserver]
3.85.176.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key

[mongodb_primary]
3.80.170.109 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.36.187

[mongodb_secondary]
3.81.105.230 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.36.118

[mongodb_secondary2]
54.152.67.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.40.28

[mongodb:children]
mongodb_primary
mongodb_secondary
mongodb_secondary2

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
