[app_server]
localhost ansible_connection=local

[webserver]
100.31.58.217 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key

[mongodb_primary]
34.204.84.38 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.39.219

[mongodb_secondary]
54.159.202.197 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.46.89

[mongodb_secondary2]
34.229.39.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mongo_key private_ip=172.31.34.167

[mongodb:children]
mongodb_primary
mongodb_secondary
mongodb_secondary2

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
